import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

function sh(cmd) {
  return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

let sha = "unknown";
try {
  sha = sh("git rev-parse --short HEAD");
} catch {}

const time = new Date().toISOString();

const outPath = join(__dirname, "../src/generated/buildInfo.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generateBuildInfo.mjs\n` +
    `export const BUILD_SHA = ${JSON.stringify(sha)} as const;\n` +
    `export const BUILD_TIME = ${JSON.stringify(time)} as const;\n`
);

console.log(`Generated ${outPath}: ${sha} @ ${time}`);
